### ISSUE TITLE
Not working when migrating to nx@19.3.2 and higher

### ISSUE THREAD

**Issue by ImriHarlev** [kfrederix/single-spa-angular-esm#2]
After migrating to higher nx version the host serve will stop being recognized.
![image](https://github.com/kfrederix/single-spa-angular-esm/assets/103680173/e8cf7aea-8328-41a2-a2bb-d77daf378298)

**Comment by kfrederix** [comment]
Hello, I am on holiday this week. Next week I can have a look, and I am planning to upgrade it to Nx 19.4.

**Comment by ImriHarlev** [comment]
Thank you for your response.

I was very impressed by your work on this template, it has it all!
The esm, importmaps and vite!
Also, using the orchestration layer is brilliant!  I'm hoping to implement
it in my project too.

If you are free to answer a few questions,  it will be very appropriated :).
I just want to be shure about the implementation.

Thank you and enjoy your holiday.

Imri

**Comment by ImriHarlev** [comment]
Thank you!

**Comment by kfrederix** [comment]
Had a look at this today, and it seems to be a bug in the Nx Vite plugin:
https://github.com/nrwl/nx/issues/26800

I'm tracking that issue now, and once it gets resolved I 'll try again to update to the latest Nx version on this repo.

**Comment by kfrederix** [comment]
Hello, just pushed an upgrade to Nx 19.5.1 + Angular 18.1.1.
(Decided to add a small patch for the @nx/vite package to unblock the upgrade, because the bug is still open and not much response. I will remove that patch file as soon as the Nx team sorts it out...)

**Comment by kfrederix** [comment]
Closing this issue now, since the upgrade is unblocked.
