### ISSUE TITLE
Have error when running dev

### ISSUE THREAD

**Issue by radonirinamaminiaina** [kfrederix/single-spa-angular-esm#3]
- I cloned the project
- I installed the deps with `yarn`
- I run `yarn dev`
- I have the following errors
![image](https://github.com/kfrederix/single-spa-angular-esm/assets/4496927/12eea928-87f5-4899-a9b6-ae289702bfb8)

**Comment by kfrederix** [comment]
Hello, could you try it with pnpm after a fresh clone?
(I have not tried with yarn so it's definitely possible that it's not working out of the box...)

**Comment by kfrederix** [comment]
Closing this, since I have no plans to support yarn in foreseeable future.

**Comment by kfrederix** [comment]
Closing this, since I have no plans to support yarn in foreseeable future.
